### ISSUE TITLE
install package binaries

### ISSUE THREAD

**Issue by dherman** [notion-cli/notion#148]
Implement installation of package binaries, e.g. `notion install cowsay`.

- [x] #170 Separate `Inventory` and `Toolchain` types
- [x] #169 Platform specs
- [x] #172 Staging area in directory layout
- [x] #173 Tool specs
- [x] #174 Generalize `Toolchain::install`
- [x] #175 Package binary case of `Toolchain::install`
- [x] #176 Create `shim` executable
