### ISSUE TITLE
Improve Error Messages and Remove Unknown Errors

### ISSUE THREAD

**Issue by charlespierce** [notion-cli/notion#294]
Tracking the progress of improving the error messages to make them more user-friendly and helpful.

Tasks
-----
- [x] #295 Audit existing error messages to improve helpfulness (PR: #336)
- [x] #296 Update calls to `.unknown` in `distro` module (PR: #344)
- [x] #297 Update calls to `.unknown` in `event` module (PR: #337)
- [x] #298 Update calls to `.unknown` in `fs` module (PR: #344)
- [x] #299 Update calls to `.unknown` in `hook` module (PR: #344)
- [x] #300 Update calls to `.unknown` in `inventory` module (PR: #344)
- [x] #301 Update calls to `.unknown` in `manifest` module (PR: #342)
- [x] #302 Update calls to `.unknown` in `platform` module (PR: #338)
- [x] #303 Update calls to `.unknown` in `project` module (PR: #339)
- [x] #304 Update calls to `.unknown` in `shell` module (PR: #340)
- [x] #305 Update calls to `.unknown` in `toolchain` module (PR: #344)
- [x] #343 Move common CTAs into constants (PR: #344)
- [x] #306 Remove `.unknown()` helper
- [x] #359 Remove `unimplemented!` and other macros that cause a panic (PR: #399)

Notes
-----
The process for updating a call to `.unknown()` is (as described in #249):
1. Add a new entry to the `ErrorDetails` enum, including information you need for the error message if necessary.
2. Update the `match` block in the `impl Display for ErrorDetails` block to include the error message for the new error.
3. Update the `match` block in the `impl NotionFail for ErrorDetails` block to return the correct `ExitCode` for the new error.
4. Replace any `.unknown()` calls that should wrap an failure in the new error with a `.with_context(|error| ErrorDetails::NewError)` call, setting any contextual values needed.
